### ISSUE TITLE
Kafka Consumer exception thrown when decoding messages using Glue Serde

### ISSUE THREAD

**Issue by fcanas-endava** [provectus/kafkaui-glue-sr-serde#23]
Hi Team,

I´m currently using an EKS cluster to manage both my MSK kafka cluster and Kafka UI within different pods. I have successfully deployed a helm chart and everything seems to be working as expected within the UI, however, when trying to decode a message using the Glue Serde the pod logs start producing the following error message:

```
	at com.provectus.kafka.ui.service.ConsumerGroupService.createConsumer(ConsumerGroupService.java:269)
	at com.provectus.kafka.ui.service.ConsumerGroupService.createConsumer(ConsumerGroupService.java:252)
	at com.provectus.kafka.ui.service.MessagesService.lambda$loadMessagesImpl$12(MessagesService.java:199)
	at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:35)
	at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14)
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8671)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The MSK and Glue Serde configuration for Kafka UI has been configured as follows:

```
yamlApplicationConfig: 
  kafka:
    clusters:
      - name: my-cluster
        bootstrapServers: :9098
        properties:
          security.protocol: SASL_SSL
          sasl.mechanism: AWS_MSK_IAM
          sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
          sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
        serde: 
          - name: GlueSchemaRegistry
            className: com.provectus.kafka.ui.serdes.glue.GlueSerde
            filePath: /path/kafkaui-glue-serde-1.0-SNAPSHOT-jar-with-dependencies.jar
            properties:
              region: us-east-1
              registry: my-registry
```

BTW the decode sometimes works but soon after the decode has been done the web connection is broken for some reason.

**Comment by sondn98** [comment]
Any update on this? Is this project abandoned?

**Comment by Haarolean** [comment]
@sondn98 https://github.com/provectus/kafka-ui/discussions/4255
